### PR TITLE
Fix caching + readme update + spec

### PR DESCRIPTION
**Pull request by piotrjaworski**
I noticed a small thing - that a cache doesn't work in fact :)

Every time, it creates a new instance of a memory store object, and during every request, it just writes a response to the memory store, but can't read from it.

Added specs, Readme update and small refactor.

### CODE REVIEW

**Comment by piotrjaworski** [comment]
@dobs Not sure if this gem is maintained anymore but I created a new PR. Cheers!

**Comment by dobs** [comment]
As the original bug might indicate, this is indeed not being maintained. :)

I’ll review the changes shortly though — and thanks for contributing!

**Comment by dobs** [comment]
Looks great, merged! The config changes are a big improvement too. Thanks again!

**Comment by piotrjaworski** [comment]
@dobs it was a pleasure :)

**Pull request merged**
